TOKEN = 'xxxx'
CONFIRMATION_TOKEN = 'xxxx'
YANDEX_DISK_DOWNLOAD_URL = 'https://cloud-api.yandex.net/v1/disk/public/resources/download'
GOOGLE_DRIVE_DOWNLOAD_URL = 'https://docs.google.com/uc'
YANDEX_DISK_TOKEN = 'xxxx'
